version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS 
  build:
    commands:
      - dotnet test ./src/HelloTests/HelloTests.csproj
      - dotnet publish -c release -o ./build_output ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
artifacts:
  files:
    - src/HelloWorldWebCore/build_output/*
    - appspec.yml
    - installApp.sh
